### ISSUE TITLE
Map status.value from velo.json to a bool to fit in the voc

### ISSUE THREAD

**Issue by stijnbrysbaert** [stijnbrysbaert/mapper#5]

**Comment by stijnbrysbaert** [comment]
```yaml      
- p: ext:actief
        o:
          value: "true"
          datatype: "xsd:boolean"
        condition:
          function: idlab-fn:equal
          parameters:
            - [grel:valueParameter, $(status.value)] # Proabably needs to be adjusted to the proper JSON structure
            - [grel:valueParameter2, "working"]
      - p: ext:actief
        o:
          value: "false"
          datatype: "xsd:boolean"
        condition:
          function: idlab-fn:notEqual
          parameters:
            - [grel:valueParameter, $(status.value)] # Same here
            - [grel:valueParameter2, "working"]
```
